export const FETCH_SONGS_LOADING = "FETCH_SONGS_LOADING";
export const FETCH_SONGS_SUCCESS = "FETCH_SONGS_SUCCESS";
export const FETCH_SONGS_ERROR = "FETCH_SONGS_ERROR";

export const TOGGLE_ACTIVE = "TOGGLE_ACTIVE";
